### PR TITLE
Moved prepending the index and registry name to the client, added the re...

### PR DESCRIPTION
**Pull request by llunved**
...levant information to the json returned by the search call to the daemon, added --no-index option to avoid listing the index

### CODE REVIEW

**Comment by llunved** [comment]
I incorporated the feedback, thanks. Please take a look now. 
UPDATE: Ignore my comment about sorting. I misunderstood how cmpSearchResults work and what it does. I fixed the sort order to be index/stars/fully qualified name, because we think that makes most sense.

**Comment by miminar** [comment]
LGTM, good job! However, I'm still concerned about omitting index column, which may produce some duplicate entries and make them appear unsorted. I'll take a stab at it.

**Comment by llunved** [comment]
On 03/12/2015 03:32 AM, Michal Minar wrote:

> LGTM, good job! However, I'm still concerned about omitting index
> column, which may produce some duplicate entries and make them appear
> unsorted. I'll take a stab at it.
> 
> I think it should be straight forward to add a filter for dupes. I am
> only aware of one scenario where it would happen though: if e.g. there
> is an image that we certify and that is hosted on docker.io.

In that case, the stars, OFFICIAL and AUTOMATED rating even will be
different, while the gully qualified URL will be identical.

Regards,

Daniel

**Comment by miminar** [comment]
@llunved please see the current [commit](https://github.com/miminar/docker/commit/1fea41026f643954469ddfc7381b35c5505e4e6f)

**Pull request merged**
